In [380]:
import pandas as pd
import numpy as np

In [381]:
df= pd.read_csv(r"C:\Users\Asus\Downloads\smartphones_cleaned_v6.csv")
df.head()

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.2,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.2,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.4,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.2,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.6,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412

In [382]:
# Analyze Data 
df.shape

(980, 26)

In [383]:
df["brand_name"].value_counts()

brand_name
xiaomi       134
samsung      132
vivo         111
realme        97
oppo          88
motorola      52
apple         46
oneplus       42
poco          41
tecno         33
iqoo          32
infinix       29
huawei        16
google        14
nokia         13
honor         13
itel          10
sony           9
asus           7
nubia          6
nothing        5
jio            4
lava           4
gionee         3
letv           3
ikall          3
redmi          3
oukitel        3
lg             3
micromax       3
royole         2
lyf            2
zte            2
lenovo         2
doogee         2
tesla          1
cola           1
leeco          1
duoqin         1
vertu          1
blu            1
leitz          1
cat            1
tcl            1
sharp          1
blackview      1
Name: count, dtype: int64

In [384]:
df["brand_name"].nunique() # number of brands

46

In [385]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   model                      980 non-null    str
 2   price                      980 non-null    int64
 3   rating                     879 non-null    float64
 4   has_5g                     980 non-null    bool
 5   has_nfc                    980 non-null    bool
 6   has_ir_blaster             980 non-null    bool
 7   processor_brand            960 non-null    str
 8   num_cores                  974 non-null    float64
 9   processor_speed            938 non-null    float64
 10  battery_capacity           969 non-null    float64
 11  fast_charging_available    980 non-null    int64
 12  fast_charging              769 non-null    float64
 13  ram_capacity               980 non-null    float64
 14  internal_memory            980 non-null    float64
 15  screen_size                980 non-null    float64
 16  refresh_rate               980 non-null    int64
 17  num_rear_cameras           980 non-null    int64
 18  num_front_cameras          976 non-null    float64
 19  os                         966 non-null    str
 20  primary_camera_rear        980 non-null    float64
 21  primary_camera_front       975 non-null    float64
 22  extended_memory_available  980 non-null    int64
 23  extended_upto              500 non-null    float64
 24  resolution_width           980 non-null    int64
 25  resolution_height          980 non-null    int64
dtypes: bool(3), float64(12), int64(7), str(4)
memory usage: 218.1 KB

In [386]:
# df[(df["fast_charging_available"]==1) & (df["fast_charging"].isnull())]
#find how many values are missing from each column 
df.isnull().sum()

brand_name                     0
model                          0
price                          0
rating                       101
has_5g                         0
has_nfc                        0
has_ir_blaster                 0
processor_brand               20
num_cores                      6
processor_speed               42
battery_capacity              11
fast_charging_available        0
fast_charging                211
ram_capacity                   0
internal_memory                0
screen_size                    0
refresh_rate                   0
num_rear_cameras               0
num_front_cameras              4
os                            14
primary_camera_rear            0
primary_camera_front           5
extended_memory_available      0
extended_upto                480
resolution_width               0
resolution_height              0
dtype: int64

In [387]:
df["fast_charging_available"].isnull().sum()

np.int64(0)

In [388]:
df[(df["brand_name"]=="apple") & (df["processor_brand"].isnull())] # a row with apple brand name and 
#missing processor brand does not exist so ,
# we can fill processor_brand with most common value

Empty DataFrame
Columns: [brand_name, model, price, rating, has_5g, has_nfc, has_ir_blaster, processor_brand, num_cores, processor_speed, battery_capacity, fast_charging_available, fast_charging, ram_capacity, internal_memory, screen_size, refresh_rate, num_rear_cameras, num_front_cameras, os, primary_camera_rear, primary_camera_front, extended_memory_available, extended_upto, resolution_width, resolution_height]
Index: []

[0 rows x 26 columns]

In [389]:
df[(df["brand_name"]=="apple" ) & (df["os"].isnull())]

Empty DataFrame
Columns: [brand_name, model, price, rating, has_5g, has_nfc, has_ir_blaster, processor_brand, num_cores, processor_speed, battery_capacity, fast_charging_available, fast_charging, ram_capacity, internal_memory, screen_size, refresh_rate, num_rear_cameras, num_front_cameras, os, primary_camera_rear, primary_camera_front, extended_memory_available, extended_upto, resolution_width, resolution_height]
Index: []

[0 rows x 26 columns]

In [390]:
df["os"].value_counts() # number of unique brands name

os
android    909
ios         46
other       11
Name: count, dtype: int64

In [391]:
df["os"].isnull().sum()

np.int64(14)

In [392]:
#columns needs to be dropped 
# 1.) fast_charging -> because of too much missing values 
#2.) smartphone name -> we will use brand name that is enough because it is impossible to do one hot encoding on smartphone name 
# 3.) rating -> customer will not know what they have to enter at this place as this value is entirely based upon customer feedback after purchasing 
# 4.) extended_upto -> again 480 values missing

In [393]:
df.drop(columns=["fast_charging","rating","extended_upto","model"],inplace=True)
df.head()

,brand_name,price,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,screen_size,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_width,resolution_height
0,oneplus,54999,True,True,False,snapdragon,8.0,3.2,5000.0,1,...,6.70,120,3,1.0,android,50.0,16.0,0,1440,3216
1,oneplus,19989,True,False,False,snapdragon,8.0,2.2,5000.0,1,...,6.59,120,3,1.0,android,64.0,16.0,1,1080,2412
2,samsung,16499,True,False,False,exynos,8.0,2.4,5000.0,1,...,6.60,90,3,1.0,android,50.0,13.0,1,1080,2408
3,motorola,14999,True,False,False,snapdragon,8.0,2.2,5000.0,1,...,6.55,120,3,1.0,android,50.0,16.0,1,1080,2400
4,realme,24999,True,False,False,dimensity,8.0,2.6,5000.0,1,...,6.70,120,3,1.0,android,108.0,16.0,0,1080,2412

In [394]:
df["processor_brand"].value_counts()

processor_brand
snapdragon    413
helio         201
dimensity     177
exynos         50
bionic         45
unisoc         26
tiger          24
google          9
kirin           7
spreadtrum      4
sc9863a         2
fusion          1
mediatek        1
Name: count, dtype: int64

In [395]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 22 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    str
 1   price                      980 non-null    int64
 2   has_5g                     980 non-null    bool
 3   has_nfc                    980 non-null    bool
 4   has_ir_blaster             980 non-null    bool
 5   processor_brand            960 non-null    str
 6   num_cores                  974 non-null    float64
 7   processor_speed            938 non-null    float64
 8   battery_capacity           969 non-null    float64
 9   fast_charging_available    980 non-null    int64
 10  ram_capacity               980 non-null    float64
 11  internal_memory            980 non-null    float64
 12  screen_size                980 non-null    float64
 13  refresh_rate               980 non-null    int64
 14  num_rear_cameras           980 non-null    int64
 15  num_front_cameras          976 non-null    float64
 16  os                         966 non-null    str
 17  primary_camera_rear        980 non-null    float64
 18  primary_camera_front       975 non-null    float64
 19  extended_memory_available  980 non-null    int64
 20  resolution_width           980 non-null    int64
 21  resolution_height          980 non-null    int64
dtypes: bool(3), float64(9), int64(7), str(3)
memory usage: 168.0 KB

In [396]:
df["num_front_cameras"].value_counts()

num_front_cameras
1.0    947
2.0     29
Name: count, dtype: int64

In [397]:
df["primary_camera_front"].max()

np.float64(60.0)

In [398]:
df[(df["brand_name"]=="apple") & (df["os"].isnull())]

Empty DataFrame
Columns: [brand_name, price, has_5g, has_nfc, has_ir_blaster, processor_brand, num_cores, processor_speed, battery_capacity, fast_charging_available, ram_capacity, internal_memory, screen_size, refresh_rate, num_rear_cameras, num_front_cameras, os, primary_camera_rear, primary_camera_front, extended_memory_available, resolution_width, resolution_height]
Index: []

[0 rows x 22 columns]

In [399]:
df[(df["brand_name"]=="apple") & (df["processor_brand"].isnull())]

Empty DataFrame
Columns: [brand_name, price, has_5g, has_nfc, has_ir_blaster, processor_brand, num_cores, processor_speed, battery_capacity, fast_charging_available, ram_capacity, internal_memory, screen_size, refresh_rate, num_rear_cameras, num_front_cameras, os, primary_camera_rear, primary_camera_front, extended_memory_available, resolution_width, resolution_height]
Index: []

[0 rows x 22 columns]

In [400]:
'''columns which has missing values 
1.) num_cores -> 6 missing -> fill with mean value 
2.) processor_speed-> 42 missing value -> fill with mean value 
3.) battery capacity -> 11 missing value -> fill with mean value 
4.) num of front cameras ->4 missing values -> fill with mode value 
5.) os-> 14 missing values -> drop 
6.) primary_camera_front -> 5 missing values -> fill with mode value  '''


from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
imputer= SimpleImputer()

transformer= ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(),["processor_speed","battery_capacity","num_cores"]),
    ('tnf2',SimpleImputer(strategy='most_frequent'),['num_front_cameras',"primary_camera_front","os","processor_brand"]),

], remainder='passthrough',verbose_feature_names_out=False)


transformed= transformer.fit_transform(df.iloc[:,:])

In [401]:
new_df=pd.DataFrame(
    transformed,
    columns=transformer.get_feature_names_out()
)

In [402]:
new_df.head()

,processor_speed,battery_capacity,num_cores,num_front_cameras,primary_camera_front,os,processor_brand,brand_name,price,has_5g,...,fast_charging_available,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,extended_memory_available,resolution_width,resolution_height
0,3.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,54999,True,...,1,12.0,256.0,6.7,120,3,50.0,0,1440,3216
1,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,19989,True,...,1,6.0,128.0,6.59,120,3,64.0,1,1080,2412
2,2.4,5000.0,8.0,1.0,13.0,android,exynos,samsung,16499,True,...,1,4.0,64.0,6.6,90,3,50.0,1,1080,2408
3,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,motorola,14999,True,...,1,6.0,128.0,6.55,120,3,50.0,1,1080,2400
4,2.6,5000.0,8.0,1.0,16.0,android,dimensity,realme,24999,True,...,1,6.0,128.0,6.7,120,3,108.0,0,1080,2412

In [403]:
counts=df["brand_name"].value_counts()

In [404]:
repl= counts[counts<10].index

In [405]:
new_df.head()

,processor_speed,battery_capacity,num_cores,num_front_cameras,primary_camera_front,os,processor_brand,brand_name,price,has_5g,...,fast_charging_available,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,extended_memory_available,resolution_width,resolution_height
0,3.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,54999,True,...,1,12.0,256.0,6.7,120,3,50.0,0,1440,3216
1,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,19989,True,...,1,6.0,128.0,6.59,120,3,64.0,1,1080,2412
2,2.4,5000.0,8.0,1.0,13.0,android,exynos,samsung,16499,True,...,1,4.0,64.0,6.6,90,3,50.0,1,1080,2408
3,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,motorola,14999,True,...,1,6.0,128.0,6.55,120,3,50.0,1,1080,2400
4,2.6,5000.0,8.0,1.0,16.0,android,dimensity,realme,24999,True,...,1,6.0,128.0,6.7,120,3,108.0,0,1080,2412

In [406]:
brand_counts = new_df['brand_name'].value_counts()

# Brands having at least 10 phones
valid_brands = brand_counts[brand_counts >= 10].index

# Replace rare brands with "Others"
new_df['brand_name'] = new_df['brand_name'].apply(
    lambda x: x if x in valid_brands else 'Others'
)
new_df["brand_name"].value_counts()

brand_name
xiaomi      134
samsung     132
vivo        111
realme       97
oppo         88
Others       77
motorola     52
apple        46
oneplus      42
poco         41
tecno        33
iqoo         32
infinix      29
huawei       16
google       14
nokia        13
honor        13
itel         10
Name: count, dtype: int64

In [407]:
new_df["processor_brand"].value_counts()

processor_brand
snapdragon    433
helio         201
dimensity     177
exynos         50
bionic         45
unisoc         26
tiger          24
google          9
kirin           7
spreadtrum      4
sc9863a         2
fusion          1
mediatek        1
Name: count, dtype: int64

In [408]:
brand_counts = new_df['processor_brand'].value_counts()

# Brands having at least 10 phones
valid_brands = brand_counts[brand_counts >= 10].index

# Replace rare brands with "Others"
new_df['processor_brand'] = new_df['processor_brand'].apply(
    lambda x: x if x in valid_brands else 'Others'
)
new_df["processor_brand"].value_counts()

processor_brand
snapdragon    433
helio         201
dimensity     177
exynos         50
bionic         45
unisoc         26
tiger          24
Others         24
Name: count, dtype: int64

In [409]:
new_df["has_5g"] = new_df["has_5g"].apply(
    lambda x: 1 if x == True else 0
)
new_df.head()

,processor_speed,battery_capacity,num_cores,num_front_cameras,primary_camera_front,os,processor_brand,brand_name,price,has_5g,...,fast_charging_available,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,extended_memory_available,resolution_width,resolution_height
0,3.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,54999,1,...,1,12.0,256.0,6.7,120,3,50.0,0,1440,3216
1,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,oneplus,19989,1,...,1,6.0,128.0,6.59,120,3,64.0,1,1080,2412
2,2.4,5000.0,8.0,1.0,13.0,android,exynos,samsung,16499,1,...,1,4.0,64.0,6.6,90,3,50.0,1,1080,2408
3,2.2,5000.0,8.0,1.0,16.0,android,snapdragon,motorola,14999,1,...,1,6.0,128.0,6.55,120,3,50.0,1,1080,2400
4,2.6,5000.0,8.0,1.0,16.0,android,dimensity,realme,24999,1,...,1,6.0,128.0,6.7,120,3,108.0,0,1080,2412

In [410]:
from sklearn.preprocessing import OneHotEncoder

In [411]:
ohe_transformer= ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(drop="first",sparse_output=False,dtype='int'),["brand_name","os","processor_brand"])
],remainder="passthrough",verbose_feature_names_out=False)

ohe_transformed= ohe_transformer.fit_transform(new_df.iloc[:,:])
new_df= pd.DataFrame(ohe_transformed,columns=ohe_transformer.get_feature_names_out())

new_df.head()

,brand_name_apple,brand_name_google,brand_name_honor,brand_name_huawei,brand_name_infinix,brand_name_iqoo,brand_name_itel,brand_name_motorola,brand_name_nokia,brand_name_oneplus,...,fast_charging_available,ram_capacity,internal_memory,screen_size,refresh_rate,num_rear_cameras,primary_camera_rear,extended_memory_available,resolution_width,resolution_height
0,0,0,0,0,0,0,0,0,0,1,...,1,12.0,256.0,6.7,120,3,50.0,0,1440,3216
1,0,0,0,0,0,0,0,0,0,1,...,1,6.0,128.0,6.59,120,3,64.0,1,1080,2412
2,0,0,0,0,0,0,0,0,0,0,...,1,4.0,64.0,6.6,90,3,50.0,1,1080,2408
3,0,0,0,0,0,0,0,1,0,0,...,1,6.0,128.0,6.55,120,3,50.0,1,1080,2400
4,0,0,0,0,0,0,0,0,0,0,...,1,6.0,128.0,6.7,120,3,108.0,0,1080,2412

In [427]:
new_df["screen_size"]

0      6
1      6
2      6
3      6
4      6
      ..
975    6
976    6
977    6
978    6
979    6
Name: screen_size, Length: 980, dtype: int64

In [428]:
len(new_df.columns)

45

In [413]:
# processor_speed -> float
new_df["processor_speed"] = pd.to_numeric(
    new_df["processor_speed"],
    errors="coerce"
).astype(float)

# remaining columns -> int
for col in new_df.columns:
    if col != "processor_speed":
        new_df[col] = pd.to_numeric(
            new_df[col],
            errors="coerce"
        ).astype(int)

In [425]:
new_df.iloc[0,:]

brand_name_apple                 0.000000
brand_name_google                0.000000
brand_name_honor                 0.000000
brand_name_huawei                0.000000
brand_name_infinix               0.000000
brand_name_iqoo                  0.000000
brand_name_itel                  0.000000
brand_name_motorola              0.000000
brand_name_nokia                 0.000000
brand_name_oneplus               1.000000
brand_name_oppo                  0.000000
brand_name_poco                  0.000000
brand_name_realme                0.000000
brand_name_samsung               0.000000
brand_name_tecno                 0.000000
brand_name_vivo                  0.000000
brand_name_xiaomi                0.000000
os_ios                           0.000000
os_other                         0.000000
processor_brand_bionic           0.000000
processor_brand_dimensity        0.000000
processor_brand_exynos           0.000000
processor_brand_helio            0.000000
processor_brand_snapdragon       1.000000
processor_brand_tiger            0.000000
processor_brand_unisoc           0.000000
processor_speed                  3.200000
battery_capacity              5000.000000
num_cores                        8.000000
num_front_cameras                1.000000
primary_camera_front            16.000000
price                           10.915088
has_5g                           1.000000
has_nfc                          1.000000
has_ir_blaster                   0.000000
fast_charging_available          1.000000
ram_capacity                    12.000000
internal_memory                256.000000
screen_size                      6.000000
refresh_rate                   120.000000
num_rear_cameras                 3.000000
primary_camera_rear             50.000000
extended_memory_available        0.000000
resolution_width              1440.000000
resolution_height             3216.000000
Name: 0, dtype: float64

In [414]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   brand_name_apple            980 non-null    int64
 1   brand_name_google           980 non-null    int64
 2   brand_name_honor            980 non-null    int64
 3   brand_name_huawei           980 non-null    int64
 4   brand_name_infinix          980 non-null    int64
 5   brand_name_iqoo             980 non-null    int64
 6   brand_name_itel             980 non-null    int64
 7   brand_name_motorola         980 non-null    int64
 8   brand_name_nokia            980 non-null    int64
 9   brand_name_oneplus          980 non-null    int64
 10  brand_name_oppo             980 non-null    int64
 11  brand_name_poco             980 non-null    int64
 12  brand_name_realme           980 non-null    int64
 13  brand_name_samsung          980 non-null    int64
 14  brand_name_tecno            980 non-null    int64
 15  brand_name_vivo             980 non-null    int64
 16  brand_name_xiaomi           980 non-null    int64
 17  os_ios                      980 non-null    int64
 18  os_other                    980 non-null    int64
 19  processor_brand_bionic      980 non-null    int64
 20  processor_brand_dimensity   980 non-null    int64
 21  processor_brand_exynos      980 non-null    int64
 22  processor_brand_helio       980 non-null    int64
 23  processor_brand_snapdragon  980 non-null    int64
 24  processor_brand_tiger       980 non-null    int64
 25  processor_brand_unisoc      980 non-null    int64
 26  processor_speed             980 non-null    float64
 27  battery_capacity            980 non-null    int64
 28  num_cores                   980 non-null    int64
 29  num_front_cameras           980 non-null    int64
 30  primary_camera_front        980 non-null    int64
 31  price                       980 non-null    int64
 32  has_5g                      980 non-null    int64
 33  has_nfc                     980 non-null    int64
 34  has_ir_blaster              980 non-null    int64
 35  fast_charging_available     980 non-null    int64
 36  ram_capacity                980 non-null    int64
 37  internal_memory             980 non-null    int64
 38  screen_size                 980 non-null    int64
 39  refresh_rate                980 non-null    int64
 40  num_rear_cameras            980 non-null    int64
 41  primary_camera_rear         980 non-null    int64
 42  extended_memory_available   980 non-null    int64
 43  resolution_width            980 non-null    int64
 44  resolution_height           980 non-null    int64
dtypes: float64(1), int64(44)
memory usage: 344.7 KB

In [429]:
new_df.columns

Index(['brand_name_apple', 'brand_name_google', 'brand_name_honor',
       'brand_name_huawei', 'brand_name_infinix', 'brand_name_iqoo',
       'brand_name_itel', 'brand_name_motorola', 'brand_name_nokia',
       'brand_name_oneplus', 'brand_name_oppo', 'brand_name_poco',
       'brand_name_realme', 'brand_name_samsung', 'brand_name_tecno',
       'brand_name_vivo', 'brand_name_xiaomi', 'os_ios', 'os_other',
       'processor_brand_bionic', 'processor_brand_dimensity',
       'processor_brand_exynos', 'processor_brand_helio',
       'processor_brand_snapdragon', 'processor_brand_tiger',
       'processor_brand_unisoc', 'processor_speed', 'battery_capacity',
       'num_cores', 'num_front_cameras', 'primary_camera_front', 'price',
       'has_5g', 'has_nfc', 'has_ir_blaster', 'fast_charging_available',
       'ram_capacity', 'internal_memory', 'screen_size', 'refresh_rate',
       'num_rear_cameras', 'primary_camera_rear', 'extended_memory_available',
       'resolution_width', 'resolution_height'],
      dtype='str')

In [415]:
new_df["price"] = np.log1p(new_df["price"])

In [416]:
new_df["price"].max()

np.float64(13.384729180332174)

In [417]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(new_df.drop(columns=["price"]),new_df["price"], test_size=0.2, random_state=42)

In [418]:
X_train.shape

(784, 44)

In [419]:
from sklearn.metrics import r2_score

In [420]:
from sklearn.ensemble import RandomForestRegressor
model_rfr= RandomForestRegressor(max_depth=5)
model_rfr.fit(X_train,y_train)

RandomForestRegressor(max_depth=5)

In [421]:
y_pred_rfr= model_rfr.predict(X_test)

In [422]:
r2_score(y_train,model_rfr.predict(X_train))

0.9135267870204212

In [423]:
r2_score(y_test,y_pred_rfr)

0.8931454382659969

In [424]:
import pickle

# Save model
with open("model_rfr.pkl", "wb") as file:
    pickle.dump(model_rfr, file)